### PR TITLE
Allow order by oldest.

### PR DESCRIPTION
**Pull request by Natim**
Refs https://github.com/mozilla-services/syncto/pull/46

r? @leplatrem

### CODE REVIEW

**Comment by almet** [comment]
The code looks good to me. However, I don't see any test attached. If there were no previous tests, we should add them.

**Comment by Natim** [comment]
Updated.

**Comment by Natim** [comment]
Test failing because of https://github.com/Frozenball/pytest-sugar/issues/71

**Comment by Natim** [comment]
pytest-sugar 0.5.1 has been released.

**Pull request merged**
