### PR TITLE
Let pass a certificate to verify SSL against when creating the client.

### PR DESCRIPTION
**Pull request by Natim**
Needed by https://github.com/mozilla-services/syncto/pull/72

### CODE REVIEW

**Comment by Natim** [comment]
See http://stackoverflow.com/a/26487178/186202

http://www.python-requests.org/en/latest/api/?highlight=verify#requests.Session.request

**Comment by almet** [comment]
hmm, I submitted a comment yesterday about this but apprently it never went trough;

From what I understand from the requests specs, the verify argument is used to pass a _bundle_ of certs. There is another `cert` argument that can be used to pass a single cert. I think we should use that instead.

**Comment by Natim** [comment]
r+ by @almet out of band.

**Pull request merged**
